version: '3.8'

services:
  web:
    environment:
      - API_BASE=http://sns_api_laravel

  api-laravel:
    container_name: sns_api_laravel
    image: nginx:latest
    working_dir: '/var/www'
    volumes:
      - './rust-sns-laravel-api:/var/www:delegated'
      - 'laravel_composer_dir:/var/www/vendor'
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8087:80'
    environment:
      TZ: Asia/Tokyo
    depends_on:
      db:
        condition: service_healthy

  php:
    container_name: sns_api_php
    build:
      context: './docker/phpfpm'
      dockerfile: 'Dockerfile'
    working_dir: '/var/www'
    volumes:
      - './rust-sns-laravel-api:/var/www:delegated'
      - 'laravel_composer_dir:/var/www/vendor'
    environment:
      DB_HOST: 'sns_db'
      DB_PORT: '3306'
      DB_DATABASE: 'database'
      DB_USERNAME: 'docker'
      DB_PASSWORD: '2C%Em%7^2L'

  composer-api:
    build:
      context: './docker/phpfpm'
      dockerfile: 'Dockerfile'
    working_dir: '/var/www'
    command: bash -c "composer install"
    volumes:
      - 'laravel_composer_dir:/var/www/vendor'
      - './rust-sns-laravel-api/storage:/var/www/storage:delegated'
      - './rust-sns-laravel-api:/var/www'

volumes:
  laravel_composer_dir:
